mv MBS_generated_sentences_5_coco.json MBS_generated_sentences_coco_5.json
mv MBS_generated_sentences_10_coco.json MBS_generated_sentences_coco_10.json
mv MBS_generated_sentences_15_coco.json MBS_generated_sentences_coco_15.json
mv MBS_generated_sentences_20_coco.json MBS_generated_sentences_coco_20.json
mv MBS_generated_sentences_25_coco.json MBS_generated_sentences_coco_25.json
mv MBS_generated_sentences_30_coco.json MBS_generated_sentences_coco_30.json
